### ISSUE TITLE
only get first image of post

### ISSUE THREAD

**Issue by t510599** [huaying/instagram-crawler#10]
Even though a post have over 1 images, it could only get the first one.

**Comment by huaying** [comment]
Hi, 

For getting all the images in posts, please use `posts_full` method.
`posts` is faster but only return limited data.
```
python crawler.py posts -u cal_foodie -n 100 -o ./output
python crawler.py posts_full -u cal_foodie -n 100 -o ./output
```

**Comment by williamkidd** [comment]
Can i repurpose the order then to another action

**Comment by t510599** [comment]
![screenshot](https://i.imgur.com/JYYXoG8.png)
I tested `posts_full`, and it still only got the first one.

**Comment by huaying** [comment]
I see. It seems that Instagram recently updated their website so that we couldn't find the rest of images.

https://github.com/huaying/instagram-crawler/pull/11
I just checked your PR. The current way to load images is like:
It will pre-load the next one but not all of them. Your way might only get 2 images mostly.

Anyway, thanks for pointing out and I will fix it  :).

**Comment by t510599** [comment]
ok, I got it!

**Comment by huaying** [comment]
@t510599 It should be fixed.
